FROM apache/airflow:2.7.3-python3.11

USER root
RUN mkdir -p /opt/dbt-venv \
    && chown airflow:0 /opt/dbt-venv

USER airflow
RUN python -m venv /opt/dbt-venv \
    && PIP_USER=false /opt/dbt-venv/bin/python -m pip install --upgrade pip \
    && PIP_USER=false /opt/dbt-venv/bin/python -m pip install --no-cache-dir \
        "dbt-core==1.12.5" \
        "dbt-athena==1.11.1" \
    && /opt/dbt-venv/bin/python -m pip check